baseURL = 'https://iuffxguy.github.io/'
languageCode = 'en-us'
title = 'philseguin.com'
theme = 'yinyang'
googleAnalytics = 'G-9PWRFZ9B2L'


[params]
  headTitle = "philseguin.com"
  [params.author]
    name = "Phil Seguin"
extraHead = ''
mainSections = ["posts"]
